Repository niftools/blender_niftools_addon, pull requests merged in 2020-05, with the labels that each got.

#340 Bug/bs effect shader controller
  .idea/markdown-doclet.xml
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
Labels: Bug, Error

#338 Fixes + mat sys improvements
  docs/user/features/armature/armature.rst
  io_scene_nif/modules/nif_export/animation/__init__.py
  io_scene_nif/modules/nif_export/animation/transform.py
  io_scene_nif/modules/nif_export/armature/__init__.py
  io_scene_nif/modules/nif_export/collision/havok.py
  io_scene_nif/modules/nif_export/constraint/__init__.py
  io_scene_nif/modules/nif_export/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_export/object/__init__.py
  io_scene_nif/modules/nif_export/property/material/__init__.py
  io_scene_nif/modules/nif_export/property/object/__init__.py
  io_scene_nif/modules/nif_export/property/texture/__init__.py
  io_scene_nif/modules/nif_export/property/texture/types/nitextureprop.py
  io_scene_nif/modules/nif_export/property/texture/writer.py
  io_scene_nif/modules/nif_export/scene/__init__.py
  io_scene_nif/modules/nif_export/types.py
  io_scene_nif/modules/nif_import/animation/transform.py
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderlightingproperty.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_nif/modules/nif_import/property/texture/__init__.py
  io_scene_nif/modules/nif_import/property/texture/types/bsshadertexture.py
  io_scene_nif/modules/nif_import/property/texture/types/nitextureprop.py
  io_scene_nif/nif_export.py
  io_scene_nif/nif_import.py
  io_scene_nif/operators/nif_export_op.py
  io_scene_nif/operators/nif_import_op.py
  io_scene_nif/properties/armature.py
  io_scene_nif/properties/scene.py
  io_scene_nif/ui/armature.py
  io_scene_nif/ui/object.py
  io_scene_nif/utils/util_math.py
Labels: Bug, Improvement, Long Term, Restructure

#341 Merge #340 to 2.8 Bug BSEffectShaderProperty shader controller
  io_scene_nif/VERSION.txt
Labels: Bug, Error

#345 Fix to BSEffectShaderProperty greyscale texture import and none-texture export
  io_scene_nif/modules/nif_export/property/texture/types/bsshadertexture.py
  io_scene_nif/modules/nif_import/property/texture/types/bsshadertexture.py
Labels: Bug

#346 Port/collision game radius
  docs/user/features/collisions/collision_objects.rst
  docs/user/features/collisions/collision_settings.rst
  io_scene_nif/modules/nif_export/collision/havok.py
  io_scene_nif/modules/nif_import/collision/__init__.py
  io_scene_nif/modules/nif_import/collision/havok.py
  io_scene_nif/ui/collision.py
Labels: Bug, Documentation, Improvement, Usability, User Interface

#347 Merge/bs effect shader missing texture fix
  io_scene_nif/modules/nif_export/property/texture/types/bsshadertexture.py
  io_scene_nif/modules/nif_import/property/texture/types/bsshadertexture.py
Labels: Bug

#348 Backport Fix Material Registration
  install/install.bat
  install/install.sh
  install/makezip.bat
  install/makezip.sh
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/geometry/niproperty.py
  io_scene_nif/modules/nif_import/property/material/__init__.py
  io_scene_nif/modules/nif_import/property/shader/__init__.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderlightingproperty.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
Labels: Bug, Critical, Improvement

#349 Collision fixes and stuff
  io_scene_nif/modules/nif_export/animation/material.py
  io_scene_nif/modules/nif_export/animation/morph.py
  io_scene_nif/modules/nif_export/collision/bound.py
  io_scene_nif/modules/nif_export/collision/havok.py
  io_scene_nif/modules/nif_export/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_export/object/__init__.py
  io_scene_nif/modules/nif_export/property/material/__init__.py
  io_scene_nif/modules/nif_export/property/object/__init__.py
  io_scene_nif/modules/nif_import/animation/material.py
  io_scene_nif/modules/nif_import/armature/__init__.py
  io_scene_nif/modules/nif_import/collision/__init__.py
  io_scene_nif/modules/nif_import/collision/bound.py
  io_scene_nif/modules/nif_import/collision/havok.py
  io_scene_nif/modules/nif_import/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_import/geometry/vertex/__init__.py
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/geometry/niproperty.py
  io_scene_nif/modules/nif_import/property/material/__init__.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_nif/nif_export.py
  io_scene_nif/nif_import.py
  io_scene_nif/operators/nif_export_op.py
  io_scene_nif/ui/armature.py
  io_scene_nif/ui/collision.py
  io_scene_nif/ui/material.py
  io_scene_nif/ui/scene.py
Labels: Bug, Error, Improvement, Long Term, New Feature, Restructure

#351 Docs/developer setup
  docs/development/setup/building.rst
  docs/development/setup/environment.rst
  docs/development/setup/ide.rst
  docs/development/setup/index.rst
  docs/development/setup/sourcecode.rst
  io_scene_nif/operators/nif_export_op.py
  io_scene_nif/operators/nif_import_op.py
  io_scene_nif/properties/armature.py
  io_scene_nif/properties/collision.py
  io_scene_nif/properties/constraint.py
  io_scene_nif/properties/geometry.py
  io_scene_nif/properties/material.py
  io_scene_nif/properties/object.py
  io_scene_nif/properties/scene.py
  io_scene_nif/properties/shader.py
Labels: Documentation, Restructure, Usability

#355 Fixes to the installation bat files
  install/install.bat
  install/makezip.bat
  testframework/install_deps.bat
Labels: Bug, Improvement

#353 Automatically select suitable axis orientation
  io_scene_nif/modules/nif_export/object/__init__.py
  io_scene_nif/modules/nif_export/property/object/__init__.py
  io_scene_nif/modules/nif_import/armature/__init__.py
  io_scene_nif/modules/nif_import/object/__init__.py
  io_scene_nif/modules/nif_import/object/types.py
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/texture/loader.py
  io_scene_nif/nif_import.py
  io_scene_nif/operators/nif_import_op.py
Labels: Improvement, New Feature, Usability

#359 Fixes to BSLightingShaderProperty
  io_scene_nif/modules/nif_export/property/shader/__init__.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_nif/properties/shader.py
  io_scene_nif/ui/shader.py
Labels: Bug, User Interface

#360 Fixes to BSLightingShaderProperty and porting of develop branch code
  io_scene_nif/modules/nif_export/collision/havok.py
  io_scene_nif/modules/nif_export/property/shader/__init__.py
  io_scene_nif/modules/nif_import/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_import/object/__init__.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_nif/properties/shader.py
  io_scene_nif/ui/shader.py
Labels: Bug, User Interface

#362 Fix/bss shader reference
  install/makezip.sh
  io_scene_nif/modules/nif_export/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_export/property/object/__init__.py
  io_scene_nif/modules/nif_export/property/shader/__init__.py
Labels: Bug

#363 Fix/bss shader node setup
  io_scene_nif/modules/nif_export/property/texture/__init__.py
  io_scene_nif/modules/nif_export/property/texture/types/bsshadertexture.py
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/geometry/niproperty.py
  io_scene_nif/modules/nif_import/property/shader/bsshaderproperty.py
Labels: Bug

#361 Feature: import pose
  io_scene_nif/modules/nif_export/armature/__init__.py
  io_scene_nif/modules/nif_export/collision/__init__.py
  io_scene_nif/modules/nif_export/geometry/mesh/__init__.py
  io_scene_nif/modules/nif_export/object/__init__.py
  io_scene_nif/modules/nif_import/armature/__init__.py
  io_scene_nif/modules/nif_import/property/geometry/mesh.py
  io_scene_nif/modules/nif_import/property/geometry/niproperty.py
  io_scene_nif/modules/nif_import/property/nodes_wrapper/__init__.py
  io_scene_nif/nif_import.py
  io_scene_nif/operators/nif_import_op.py
  io_scene_nif/ui/scene.py
  io_scene_nif/utils/util_math.py
Labels: New Feature
