Repository niftools/blender_niftools_addon, pull requests merged in 2020-11, with the labels that each got.

#385 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/pull-request.md
Labels: Improvement, New Feature

#386 Feature/auto updater
  io_scene_niftools/__init__.py
  io_scene_niftools/addon_updater.py
  io_scene_niftools/addon_updater_ops.py
  io_scene_niftools/prefs/__init__.py
  io_scene_niftools/update.py
  io_scene_niftools/utils/updater/__init__.py
Labels: Improvement, New Feature, Usability, User Interface

#388 Feature/Automate Release Process
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
  .github/workflows/release_on_tag.yml
  .github/workflows/release_pr_content.yml
Labels: Improvement, New Feature, Usability

#391 Release/v0.0.2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SUPPORT.md
  .github/workflows/initial_interaction.yml
  .github/workflows/release_on_tag.yml
  .github/workflows/release_pr_content.yml
  io_scene_niftools/VERSION.txt
  io_scene_niftools/__init__.py
  io_scene_niftools/nif_export.py
Labels: Release

#389 Updating Sphinx Documentation
  .gitignore
  CHANGELOG.rst
  CONTRIBUTING.rst
  LICENSE.rst
  README.rst
  docs/_static/images/NifTools_Install.gif
  docs/additional/authors.rst
  docs/additional/changes.rst
  docs/additional/contributing.rst
  docs/additional/index.rst
  docs/additional/license.rst
  docs/conf.py
  docs/development/api/index.rst
  docs/development/design/conventions.rst
  docs/development/design/index.rst
  docs/development/design/issues.rst
  docs/development/design/overview.rst
  docs/development/design/workflow.rst
  docs/development/docs.rst
  docs/development/index.rst
  docs/development/setup/building.rst
  docs/development/setup/environment.rst
  docs/development/setup/ide.rst
  docs/development/setup/index.rst
  docs/development/setup/sourcecode.rst
  docs/development/testframework/api/index.rst
  docs/development/testframework/ci_server.rst
  docs/development/testframework/design/index.rst
  docs/development/testframework/design/integration.rst
  docs/development/testframework/index.rst
  docs/index.rst
  docs/user/features/armature/armature.rst
  docs/user/features/collisions/collision_objects.rst
  docs/user/features/collisions/collision_settings.rst
  docs/user/features/collisions/index.rst
  docs/user/features/geometry/geometry.rst
  docs/user/features/index.rst
  docs/user/features/iosettings/export.rst
  docs/user/features/iosettings/import.rst
  docs/user/features/iosettings/index.rst
  docs/user/features/object/index.rst
  docs/user/features/properties/index.rst
  docs/user/features/properties/material.rst
  docs/user/features/properties/niproperty.rst
  docs/user/features/properties/shader/index.rst
  docs/user/features/properties/textures/index.rst
  docs/user/features/properties/textures/texture_maps.rst
  docs/user/features/scene/index.rst
  docs/user/index.rst
  docs/user/install.rst
  docs/user/support.rst
  docs/user/ui/index.rst
  docs/user/workflow.rst
Labels: Documentation, Improvement

#366 Feature/operator interface
  .DS_Store
  docs/user/features/iosettings/index.rst
  docs/user/features/scene/index.rst
  install/.DS_Store
  io_scene_niftools/__init__.py
  io_scene_niftools/modules/nif_import/property/geometry/mesh.py
  io_scene_niftools/modules/nif_import/property/nodes_wrapper/__init__.py
  io_scene_niftools/modules/nif_import/property/shader/__init__.py
  io_scene_niftools/modules/nif_import/property/shader/bsshaderlightingproperty.py
  io_scene_niftools/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_niftools/nif_export.py
  io_scene_niftools/nif_import.py
  io_scene_niftools/operators/common_op.py
  io_scene_niftools/operators/egm_import_op.py
  io_scene_niftools/operators/kf_export_op.py
  io_scene_niftools/operators/kf_import_op.py
  io_scene_niftools/operators/nif_export_op.py
  io_scene_niftools/operators/nif_import_op.py
  io_scene_niftools/properties/scene.py
  io_scene_niftools/ui/__init__.py
  io_scene_niftools/ui/geometry.py
  io_scene_niftools/ui/operator.py
  io_scene_niftools/ui/scene.py
Labels: Documentation, Improvement, Usability, User Interface
