Repository niftools/blender_niftools_addon, pull requests merged in 2021-04, with the labels that each got.

#430 Release/v0.0.5
  .github/workflows/release_on_tag.yml
  io_scene_niftools/modules/nif_import/geometry/vertex/__init__.py
  io_scene_niftools/ui/operators/nif_import.py
  io_scene_niftools/utils/debugging.py
Labels: Bug, Usability

#426 Minor animation export bugs fixed
  io_scene_niftools/modules/nif_export/animation/transform.py
Labels: Bug

#435 Release/v0.0.5
  .github/workflows/release_on_tag.yml
  CHANGELOG.rst
  io_scene_niftools/VERSION.txt
  io_scene_niftools/__init__.py
Labels: Bug, Release

#438 Cleanup of uv transform handling and texture slot name use, and change to glossiness import
  docs/user/features/properties/material.rst
  io_scene_niftools/modules/nif_export/property/material/__init__.py
  io_scene_niftools/modules/nif_export/property/shader/__init__.py
  io_scene_niftools/modules/nif_export/property/texture/__init__.py
  io_scene_niftools/modules/nif_export/property/texture/types/bsshadertexture.py
  io_scene_niftools/modules/nif_import/property/material/__init__.py
  io_scene_niftools/modules/nif_import/property/nodes_wrapper/__init__.py
  io_scene_niftools/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_niftools/modules/nif_import/property/texture/types/bsshadertexture.py
  io_scene_niftools/modules/nif_import/property/texture/types/nitextureprop.py
  io_scene_niftools/utils/consts.py
Labels: Improvement, New Feature, Restructure, Usability

#434 Use updated niftools_sphinx_theme
  .readthedocs.yaml
  CHANGELOG.rst
  docs/Makefile
  docs/blender-sphinx-api-build.py
  docs/blender-sphinx-build.py
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  docs/user/features/index.rst
Labels: Documentation

#439 Updates to partition generation and object properties
  docs/user/features/armature/armature.rst
  docs/user/features/object/index.rst
  io_scene_niftools/modules/nif_export/animation/__init__.py
  io_scene_niftools/modules/nif_export/geometry/mesh/__init__.py
  io_scene_niftools/modules/nif_export/geometry/mesh/skin_partition.py
  io_scene_niftools/modules/nif_export/object/__init__.py
  io_scene_niftools/modules/nif_export/property/object/__init__.py
  io_scene_niftools/modules/nif_import/animation/__init__.py
  io_scene_niftools/modules/nif_import/geometry/vertex/groups.py
  io_scene_niftools/modules/nif_import/object/__init__.py
  io_scene_niftools/modules/nif_import/property/object/__init__.py
  io_scene_niftools/modules/nif_import/scene/__init__.py
  io_scene_niftools/operators/geometry.py
  io_scene_niftools/properties/__init__.py
  io_scene_niftools/properties/geometry.py
  io_scene_niftools/properties/object.py
  io_scene_niftools/ui/__init__.py
  io_scene_niftools/ui/geometry.py
  io_scene_niftools/ui/object.py
Labels: Bug, Improvement, New Feature, Usability, User Interface
