Repository niftools/blender_niftools_addon, pull requests merged in 2021-11, with the labels that each got.

#483 Release/v0.0.11
  CHANGELOG.rst
  docs/user/features/object/index.rst
  io_scene_niftools/VERSION.txt
  io_scene_niftools/__init__.py
  io_scene_niftools/addon_updater_ops.py
  io_scene_niftools/kf_import.py
  io_scene_niftools/modules/nif_export/armature/__init__.py
  io_scene_niftools/modules/nif_export/geometry/mesh/__init__.py
  io_scene_niftools/modules/nif_export/object/__init__.py
  io_scene_niftools/modules/nif_export/property/shader/__init__.py
  io_scene_niftools/modules/nif_export/property/texture/types/bsshadertexture.py
  io_scene_niftools/modules/nif_export/property/texture/writer.py
  io_scene_niftools/modules/nif_import/armature/__init__.py
  io_scene_niftools/modules/nif_import/object/__init__.py
  io_scene_niftools/modules/nif_import/property/nodes_wrapper/__init__.py
  io_scene_niftools/modules/nif_import/property/shader/bsshaderproperty.py
  io_scene_niftools/modules/nif_import/property/texture/loader.py
  io_scene_niftools/nif_export.py
  io_scene_niftools/nif_import.py
  io_scene_niftools/properties/collision.py
  io_scene_niftools/properties/object.py
  io_scene_niftools/properties/shader.py
  io_scene_niftools/ui/object.py
  io_scene_niftools/ui/shader.py
  io_scene_niftools/utils/math.py
Labels: Bug

#481 Anim system improvements
  io_scene_niftools/kf_import.py
  io_scene_niftools/modules/nif_export/animation/__init__.py
  io_scene_niftools/modules/nif_export/animation/transform.py
  io_scene_niftools/modules/nif_export/armature/__init__.py
  io_scene_niftools/modules/nif_export/collision/havok.py
  io_scene_niftools/modules/nif_import/animation/__init__.py
  io_scene_niftools/modules/nif_import/animation/material.py
  io_scene_niftools/modules/nif_import/animation/object.py
  io_scene_niftools/modules/nif_import/animation/transform.py
  io_scene_niftools/modules/nif_import/armature/__init__.py
  io_scene_niftools/nif_export.py
  io_scene_niftools/nif_import.py
  io_scene_niftools/utils/math.py
Labels: New Feature, Improvement, Bug

#484 Pull out nifformat_to_mathutils_matrix, improve comment
  io_scene_niftools/modules/nif_import/armature/__init__.py
  io_scene_niftools/utils/math.py
Labels: Improvement, Restructure

#485 Release/v0.0.12
  CHANGELOG.rst
  io_scene_niftools/VERSION.txt
  io_scene_niftools/__init__.py
  io_scene_niftools/kf_import.py
  io_scene_niftools/modules/nif_export/animation/__init__.py
  io_scene_niftools/modules/nif_export/animation/transform.py
  io_scene_niftools/modules/nif_export/armature/__init__.py
  io_scene_niftools/modules/nif_export/collision/havok.py
  io_scene_niftools/modules/nif_import/animation/__init__.py
  io_scene_niftools/modules/nif_import/animation/material.py
  io_scene_niftools/modules/nif_import/animation/object.py
  io_scene_niftools/modules/nif_import/animation/transform.py
  io_scene_niftools/modules/nif_import/armature/__init__.py
  io_scene_niftools/nif_export.py
  io_scene_niftools/nif_import.py
  io_scene_niftools/utils/math.py
Labels: Improvement, Bug, Release
